server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yami_shops?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 25000
      auto-commit: true
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
      database: ${REDIS_DATABASE:0}
logging:
  config: classpath:logback/logback-prod.xml
xxl-job:
  accessToken: default_token
  logPath: /data/applogs/xxl-job/jobhandler
  admin:
    addresses: http://localhost:8080/xxl-job-admin
